config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    resources :reports do
      collection do
        post :import
      end
    end
  end
  root to: "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
end

app/models/report/import.rb
class Report::Import
  include ActiveModel::Model

  attr_accessor :file, :imported_count

  def process!
    @imported_count = 0
    CSV.foreach(file.path, headers: true, header_converters: :symbol) do |row|
      report = Report.asign_from_row(row)
      if report.save
        @imported_count += 1
      else
        errors.add(:base, "Line #{$.} - #{report.errors.full_messages.join(',')}")
      end
    end
    counter
  end

  def save
    process!
    errors.none?
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reports
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reports_controller.rb
class ReportsController < ActionController::Base
  def index
    @reports = Report.all
    @import = Report::Import.new
  end

  def import
    @import = Report::Import.new report_import_params
    if @import.save
      redirect_to users_path, notice: "Imported #{@import.imported_count} transactions"
    else
      @reports = Report.all
      flash[:alert] = "There were #{@import.errors.count} errors with your CSV file"
      render action: :index
    end
  end

  def create
    user = User.find_or_create_by(name: params[:report][:comprador])
    Report.create(comprador: report_params[:report][:comprador], user: user)
  end

  private

  def user_import_params
    params.require(:report_import).permit(:file)
  end

  def report_params
    params.require(:report).permit(:user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ActionController::Base
  def index
    @user = User.new
    @user.save
    @reports = @user.reports.all
  end

  def self.assign_from_row(row)
    report = Report.where(comprador: row[:comprador]).first_or_initialize
    report.assign_attributes row.to_hash.slice(:comprador, :descripcion_del_item, :precio_del_item, :total_de_items, :direccion_del_vendedor, :vendedor)
    report
  end

  def create
    @user = User.new(params[:user])
    #flash[:success] = 'User already exists.'
    if @user.save
      session[:user_id] = @user.id
      @current_user = User.find(session[:user_id])
      @report = @current_user.reports.create
      flash[:success] = 'New User created.'
      redirect_to 'user#index'
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TsvUploader</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_index.html.haml
%h1 All Reports!
%table
  %tr
    %th Comprador
    %th Descripción del Item
    %th Precio del Item
    %th Total de Items
    %th Dirección del vendedor
    %th Vendedor
  %tr
    - @reports.each do |transaction|
      %tr
        %td= transaction.comprador
        %td= transaction.descripcion_del_item
        %td= transaction.precio_del_item
        %td= transaction.total_de_items
        %td= transaction.direccion_del_vendedor
        %td= transaction.vendedor
= form_tag import_user_reports_path(@users, @reports), action: :import, method: :post, multipart: true do |f|
  = f.label :file
  = f.file_field :file
  = f.submit_tag 'Upload'

app/views/users/index.html.erb
<h1>All Reports!</h1>
<table>
  <tr>
    <th>Comprador</th>
    <th>Descripción del Item</th>
    <th>Precio del Item</th>
    <th>Total de Items</th>
    <th>Dirección del vendedor</th>
    <th>Vendedor</th>
  </tr>
  <tbody>
    <%= @user.reports.each do |transaction| %>
      <tr>
        <%= content_tag :td, transaction.comprador %>
        <%= content_tag :td, transaction.descripcion_del_item %>
        <%= content_tag :td, transaction.precio_del_item %>
        <%= content_tag :td, transaction.total_de_items %>
        <%= content_tag :td, transaction.direccion_del_vendedor %>
        <%= content_tag :td, transaction.vendedor %>
      <tr>
    <% end %>
  </tbody>
<%= form_for import_user_reports_path(@user, @report), multipart: true do |f| %>
  <%= f.label :file %>
  <%= f.file_field :file %>
  <%= f.submit 'Upload' %>
<% end %>

app/views/users/index.html.haml
%h1 All Reports!

%table.table.table-striped.table-bordered
  %thead
    %th Comprador
    %th Descripción del Item
    %th Precio del Item
    %th Total de Items
    %th Dirección del vendedor
    %th Vendedor
  %tbody
    - @reports.each do |transaction|
      %tr
        %td= transaction.comprador
        %td= transaction.descripcion_del_item
        %td= transaction.precio_del_item
        %td= transaction.total_de_items
        %td= transaction.direccion_del_vendedor
        %td= transaction.vendedor

- form_with url: import_user_reports_path, method: :post, multipart: true do |f|
  = f.file_field :file
  = submit_tag 'Upload'